### ISSUE TITLE
Allow props reassignment

### ISSUE THREAD

**Issue by ciainis** [edenspiekermann/espi-eslint-config#19]
The `no-param-reassign` rule does not allow props reassignment.

To fix the behaviour and allow props reassignment, add the following rule: `'no-param-reassign': ['error', { 'props': false }]`

**Comment by schorfES** [comment]
```
function sum (a, b) {
  a += b;
  return a;
}
```

**Comment by schorfES** [comment]
This is too edge case. We will not enable this.
