### ISSUE TITLE
Add React Hooks plugin to list of plugins

### ISSUE THREAD

**Issue by kojinkai** [edenspiekermann/espi-eslint-config#6]
https://www.npmjs.com/package/eslint-plugin-react-hooks

**Comment by schorfES** [comment]
Hi @kojinkai, i think this is fixed in [release 1.0.0](https://github.com/edenspiekermann/espi-eslint-config/compare/v0.1.2...v1.0.0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R59)?
