### ISSUE TITLE
Deprecated Feature Warning: ESLINT_LEGACY_OBJECT_REST_SPREAD

### ISSUE THREAD

**Issue by jankohofmann** [edenspiekermann/espi-eslint-config#7]
When running `eslint` with the espi config, the following warning appears:
```
(node:3767) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The
'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use
'parserOptions.ecmaVersion' instead. (found in "node_modules/eslint-config-airbnb-base/index.js")
```

Probably due to an outdated version of the Airbnb config.

**Comment by schorfES** [comment]
Hi @jankohofmann, there is a [new release](https://github.com/edenspiekermann/espi-eslint-config/releases/tag/v1.0.0) with a lot new "features" und updates of dependencies. Can you try this version and test if this resolves your problem?
